### ISSUE TITLE
`econdata_tidy_release()`

### ISSUE THREAD

**Issue by aidanhorn** [coderaanalytics/econdatar#15]
When using `read_release( tidy = TRUE)` in version 2.0.0, I get the error
> Empty data.table (0 rows and 1 cols): date

Can you please double-check [`econdata_tidy_release()`](https://github.com/coderaanalytics/econdatar/blob/4076a0d265338220fc95e93ed7d7fc529d4897c0/R/econdata_tidy.R#L101)?

**Comment by aidanhorn** [comment]
@byrongibby are you still working on this?

**Comment by byrongibby** [comment]
Please try version 2.0.4
