### ISSUE TITLE
econdatapy?

### ISSUE THREAD

**Issue by kristoffPotgieter** [coderaanalytics/econdatar#2]
Hi is there any chance that this library will be made available for python?

**Comment by byrongibby** [comment]
Yes, this is definitely in the pipeline. I will post updates here soon

**Comment by byrongibby** [comment]
Due to other commitments this is currently on hold.

**Comment by byrongibby** [comment]
https://github.com/coderaanalytics/econdatapy

**Comment by byrongibby** [comment]
https://econdata.co.za/introducing-econdatas-python-package/
