### ISSUE TITLE
`read_econdata(wide=TRUE)` doesn't include `period`

### ISSUE THREAD

**Issue by aidanhorn** [coderaanalytics/econdatar#21]
@byrongibby I'm helping @Hendrivanz now. The standard code when exporting on www.econdata.co.za doesn't specify `wide=FALSE`, but then we don't see the period (date information) when pulling the data. Can you please check that the period data is supplied when `wide=TRUE`?
We were both using version `2.2.0`.

**Comment by byrongibby** [comment]
`period` has been renamed `time_period` to be more consistent with the description of the data in the data registry.

**Comment by aidanhorn** [comment]
Please open this issue again, and show where the `time_period` is in
```r
library(econdatar)

data_raw <- read_econdata(id = "NATL_ACC",
                          wide = TRUE)
str(data_raw)
```

**Comment by byrongibby** [comment]
Please try 

```
library(econdatar)

data_raw <- read_econdata(id = "NATL_ACC",
                                             tidy = TRUE,
                                             wide = TRUE)
str(data_raw)
```
The `wide` argument has no meaning without `tidy=TRUE`.
