### ISSUE TITLE
Incompatibility with latest Ubuntu LTS OS, until 25 April 2024

### ISSUE THREAD

**Issue by aidanhorn** [coderaanalytics/econdatar#32]
`r-base` in Ubuntu Jammy (22.04LTS) is [version 4.1.2](https://packages.ubuntu.com/jammy/r-base). However, the `_` placeholder used in [read_registry.R](https://github.com/coderaanalytics/econdatar/blob/master/R/read_registry.R) and [get_metadata.R](https://github.com/coderaanalytics/econdatar/blob/master/R/get_metadata.R) is a feature that was only [introduced from R version 4.2.0](https://www.r-bloggers.com/2022/04/new-features-in-r-4-2-0/) onwards. Thus, Ubuntu users must use a newer OS version than 22. The next LTS version will be released [on 25 April 2024](https://discourse.ubuntu.com/t/noble-numbat-release-schedule/35649).

**Comment by byrongibby** [comment]
[Added minimum R version required](https://github.com/coderaanalytics/econdatar/commit/78ef2b959d92302d6ba09f7444d0b5a877c186bb)
