### ISSUE TITLE
PPI metadata mismatch

### ISSUE THREAD

**Issue by WihanZA** [coderaanalytics/econdatar#34]
Hi Codera Team
I was trying out some data fetching with the econdatar package and came across some metadata mismatches for the SARB's PPI data. Specifically, series names and labels do not seem aligned. The same is true for the data tables on econdata.co.za.
Wasn't sure where to raise the issue, so I came here.
![Screenshot 2024-05-24 082052](https://github.com/coderaanalytics/econdatar/assets/79515224/0d39e4c1-3e81-424e-8c9c-6f9b29776f8d)
Keep up the good and useful work!

**Comment by aidanhorn** [comment]
Thank you very much @WihanZA for pointing this out 😊. @byrongibby, the `CL_PPI` codelist version for MNEMONIC is still on 1.0.0 in the data structure, whereas the latest 1.1.0 has PPI028 = "Petrol".

I will update the data structure, and also create an Issue internally for us to review if this problem exists for any other dataflows.

**Comment by aidanhorn** [comment]
I've pushed a fix to a private repo. I'm just waiting for approval before running it.

**Comment by byrongibby** [comment]
Thanks, please do go ahead.

**Comment by aidanhorn** [comment]
The data structure has been corrected now. Please refresh the website before checking.
